# Generated by Django 4.1.4 on 2022-12-17 20:25

import books.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=books.models.upload_image_book),
        ),
        migrations.AlterField(
            model_name='books',
            name='id_book',
            field=models.UUIDField(default=uuid.UUID('63d97404-c71c-487b-a5c1-c73b8c38fa5a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
